spring:
  cloud:
    gateway:
      routes:
        - id: nserver
          uri: http://localhost:8080
          predicates:
            - Path=/server/**
          filters:
            - RewritePath=/server/(?<segment>.*), /api/v1/${segment}

        - id: ui
          uri: http://localhost:3000
          predicates:
            - Path=/ui/**
          filters:
            - RewritePath=/ui/(?<segment>.*), /${segment}

        - id: ui-js-assets
          uri: http://localhost:3000
          predicates:
            - Path=/static/js/**
          filters:
            - RewritePath=/static/js/(?<filename>.*), /static/js/${filename}


      globalcors:
        corsConfigurations:
          '[/**]':
            allowed-origins: "http://localhost:5000"  # Updated to reflect the gateway's address if served through the gateway.
            allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
            allowed-headers: "Authorization, Content-Type, Accept"
            allow-credentials: true
            max-age: 1800 # 30 minutes

  application:
    name: gateway

server:
  port: 5000

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.web.cors: DEBUG
    org.springframework.cloud.gateway: DEBUG
