spring:
  cloud:
    gateway:
      routes:
        - id: nserver
          uri: http://localhost:8080
          predicates:
            - Path=/server/**
          filters:
            - RewritePath=/server/(?<segment>.*), /api/v1/$\{segment}
      globalcors:
        corsConfigurations:
          '[/]':
            allowedOrigins:
              - http://localhost:3000
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Content-Type
              - Authorization
              - X-Requested-With
              - Accept
              - Origin
            allowCredentials: true
            maxAge: 3600

  application:
    name: gateway

server:
  port: 5000

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE